Using TensorFlow backend.
2019-06-19 00:30:09.664020: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-19 00:30:09.684804: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691870000 Hz
2019-06-19 00:30:09.685394: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55ee0d6c37d0 executing computations on platform Host. Devices:
2019-06-19 00:30:09.685419: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-19 00:30:09.759871: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55ee0d6893b0 executing computations on platform CUDA. Devices:
2019-06-19 00:30:09.759905: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-19 00:30:09.760177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 7.68GiB
2019-06-19 00:30:09.760193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-19 00:30:09.760838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-19 00:30:09.760855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-19 00:30:09.760861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-19 00:30:09.761102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7472 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-19 00:30:12.820146: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
Traceback (most recent call last):
  File "foolbox_exp/experiment.py", line 101, in <module>
    adversarial = attack(x_sample, np.argmax(y_sample, axis=1), binary_search_steps=5, max_iterations=600)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 34, in __call__
    distance=distance, threshold=threshold, **kwargs)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batching.py", line 58, in run_parallel
    x = attack.send(result)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 57, in wrapper
    _ = yield from generator(self, a, **kwargs)
TypeError: as_generator() got an unexpected keyword argument 'binary_search_steps'
Using TensorFlow backend.
2019-06-19 00:33:09.364627: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-19 00:33:09.388877: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3691870000 Hz
2019-06-19 00:33:09.389568: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55fa3f73aa50 executing computations on platform Host. Devices:
2019-06-19 00:33:09.389606: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-19 00:33:09.477743: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55fa3e266510 executing computations on platform CUDA. Devices:
2019-06-19 00:33:09.477787: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2019-06-19 00:33:09.478062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:03:00.0
totalMemory: 11.93GiB freeMemory: 7.34GiB
2019-06-19 00:33:09.478079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-19 00:33:09.478713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-19 00:33:09.478728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-19 00:33:09.478734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-19 00:33:09.478908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7142 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0, compute capability: 5.2)
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /vol/gpudata/ap8415/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-06-19 00:33:13.316214: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.9.0 locally
Traceback (most recent call last):
  File "foolbox_exp/experiment.py", line 101, in <module>
    adversarial = attack(x_sample, np.argmax(y_sample, axis=1), binary_search_steps=5, max_iterations=600)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 34, in __call__
    distance=distance, threshold=threshold, **kwargs)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batching.py", line 58, in run_parallel
    x = attack.send(result)
  File "/vol/gpudata/ap8415/adversarial-robustness-toolbox/foolbox/batch_attacks/base.py", line 57, in wrapper
    _ = yield from generator(self, a, **kwargs)
TypeError: as_generator() got an unexpected keyword argument 'binary_search_steps'
